const chat = [
    {
        id: 'chaos',
        numId: 0,
        message: '0Hello, i am bot chaous, write something me 1', 
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 1,
        type: 'links',
        message: '1If you want now more, go by link https://netology.ru/, connect to our funy company 2',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 2,
        type: 'links',
        message: '2If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 3,
        type: 'links',
        message: '3If you want now more, go by link https://netology.ru/, connect to our funy company 3If you want now more, go by link https://netology.ru/, connect to our funy company 3If you want now more, go by link https://netology.ru/, connect to our funy company 3If you want now more, go by link https://netology.ru/, connect to our funy company 3If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 4,
        type: 'links',
        message: '4If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 5,
        type: 'links',
        message: '5If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 6,
        type: 'links',
        message: '6If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 7,
        type: 'links',
        message: '7If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 8,
        type: 'links',
        message: '8If you want now more, go by link https://netology.ru/, connect to our funy company', 
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 9,
        type: 'links',
        message: '9If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 10,
        type: 'links',
        message: '10Hello, i am bot chaous, write something me',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 11,
        type: 'links',
        message: '11If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 12,
        type: 'links',
        message: '12If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 13,
        type: 'links',
        message: '13If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 14,
        type: 'links',
        message: '14If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 15,
        type: 'links',
        message: '15If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 16,
        type: 'links',
        message: '16If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 17,
        type: 'links',
        message: '17If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 18,
        type: 'links',
        message: '18If you want now more, go by link https://netology.ru/, connect to our funy company', 
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 19,
        type: 'links',
        message: '19If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 20,
        type: 'links',
        message: '20Hello, i am bot chaous, write something me',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 21,
        type: 'links',
        message: '21If you want now more, go by link https://netology.ru/, connect to our funy company 21If you want now more, go by link https://netology.ru/, connect to our funy company 21If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 22,
        type: 'links',
        message: '22If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 23,
        type: 'links',
        message: '23If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 24,
        type: 'links',
        message: '24If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 25,
        type: 'links',
        message: '25If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 26,
        type: 'links',
        message: '26If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 27,
        type: 'links',
        message: '27If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 28,
        type: 'links',
        message: '28If you want now more, go by link https://netology.ru/, connect to our funy company', 
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 29,
        type: 'links',
        message: '29If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 30,
        type: 'links',
        message: '30If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 32,
        type: 'links',
        message: '32If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 33,
        type: 'links',
        message: '33If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 34,
        type: 'links',
        message: '34If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 35,
        type: 'links',
        message: '35If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 36,
        type: 'links',
        message: '36If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 37,
        type: 'links',
        message: '37If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
    {
        id: 'chaos',
        numId: 38,
        type: 'links',
        message: '38If you want now more, go by link https://netology.ru/, connect to our funy company',
        date: '20.05.23',
    },
];

module.exports = {
    chat
}